server:
  port: 2003
spring:
  application:
    name: seata-account-service
  output:
    ansi:
      enabled: always
  cloud:
    alibaba:
      seata:
        #自定义事务组名称，需要与seata-server配置文件中的一致
        tx-service-group: fsp_tx_group
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seata_account?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 15576123138
feign:
  hystrix:
    enabled: true
logging:
  level:
    io:
      seata: info
    com:
      tomshidi:
        springcloud:
          dao: debug
mybatis:
#  mapper-locations: classpath*:mapper/*.xml
  mapperLocations: classpath*:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


