server:
  port: 9002
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.88.130:1111 #nginx集群地址
  output:
    ansi:
      enabled: always
  application:
    name: nacos-payment-provider
management:
  endpoints:
    web:
      exposure:
        include: '*'

