server:
  port: 9002
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  output:
    ansi:
      enabled: always
  application:
    name: nacos-payment-provider
management:
  endpoints:
    web:
      exposure:
        include: '*'

