server:
  port: 9527
spring:
  output:
    ansi:
      enabled: always
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
      - id: payment_route  #路由id，没有固定规则，但是要求唯一
#        uri: http://localhost:8001  #匹配后提供服务的路由地址
        uri: lb://cloud-payment-service
        predicates:
        - Path=/payment/get/**   #断言，路径匹配规则
#        - After=2020-07-07T15:04:05.179+08:00[Asia/Shanghai]
#        - Cookie=username,tom
#        - Header=X-Request-Id,\d+
        filter:
          -AddRequestParameter=name,11111
      - id: payment_route2
#        uri: http://localhost:8001
        uri: lb://cloud-payment-service
        predicates:
        - Path=/payment/port/**
#        - After=2020-07-07T15:04:05.179+08:00[Asia/Shanghai]
#        - Cookie=username,tom
#        - Header=X-Request-Id,\d+
        filter:
          -AddRequestParameter=X-Request-Id,11111


eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
    register-with-eureka: true
    fetch-registry: true


